adminUser:
  password: vault:pr-452-2arc/adminUser:password
  username: admin
dashboardAuthID: vault:pr-452-2arc:dashboardAuthID
dashboardAuthOrg: arcalos-dashboard
dashboardAuthSecret: vault:pr-452-2arc:dashboardAuthSecret
dashboardGrpchost: dex.jx
enableDocker: false
pipelineUser:
  email: jenkins-x@googlegroups.com
  token: vault:pr-452-2arc/pipelineUser:token
  username: jenkins-x-bot-test
prow:
  hmacToken: vault:pr-452-2arc/prow:hmacToken
segmentWriteKey: vault:pr-452-2arc:segmentWriteKey
